app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    
app_homepage2:
    path:     /{nombre}
    defaults: { _controller: AppBundle:Default:index }

app_confirmation:
    path:     /confirm/
    defaults: { _controller: AppBundle:Default:confirm }

